; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Games:A/AfricanRaiders01/AfricanRaiders01.Slave

; Favourites Mode
IF EXISTS ENV:favouritesmode
  execute S:AGS2Favourites "A" "African Raiders-01"
  IF $favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Games:A/AfricanRaiders01/"
IF EXISTS ENV:whdloadargs
  whdload "AfricanRaiders01.Slave" $whdloadargs
ELSE
  whdload "AfricanRaiders01.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
