; AGS2 run script
; ---------------
;RunFile=A-Games:H/Hacker2/Hacker2.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "H" "Hacker II The Doomsday Pap"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:H/Hacker2/"
IF EXISTS ENV:whdloadargs
  whdload "Hacker2.Slave" $whdloadargs
ELSE
  whdload "Hacker2.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
