; AGS2 run script
; ---------------
;RunFile=A-Games:H/HackerNTSC/HackerNTSC.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "H" "Hacker NTSC"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:H/HackerNTSC/"
IF EXISTS ENV:whdloadargs
  whdload "HackerNTSC.Slave" $whdloadargs
ELSE
  whdload "HackerNTSC.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
