; AGS2 run script
; ---------------
;RunFile=A-Games:F/Fuzzball/Intro.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "F" "Fuzzball Intro"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:F/Fuzzball/"
IF EXISTS ENV:whdloadargs
  whdload "Intro.Slave" $whdloadargs
ELSE
  whdload "Intro.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
