; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Games:N/NuclearWar/NuclearWar.Slave

; Favourites Mode
IF EXISTS ENV:favouritesmode
  execute S:AGS2Favourites "N" "Nuclear War"
  IF $favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Games:N/NuclearWar/"
IF EXISTS ENV:whdloadargs
  whdload "NuclearWar.Slave" $whdloadargs
ELSE
  whdload "NuclearWar.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
