; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Games:T/TestDrive2/TestDrive2.slave

; Favourites Mode
IF EXISTS ENV:favouritesmode
  execute S:AGS2Favourites "T" "Test Drive II The Duel"
  IF $favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Games:T/TestDrive2/"
IF EXISTS ENV:whdloadargs
  whdload "TestDrive2.slave" $whdloadargs
ELSE
  whdload "TestDrive2.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
