; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Games:A/AotGSAFP27b6/AotGSAFP27b6.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "T" "The Attack of the Green Sm"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:A/AotGSAFP27b6/"
IF EXISTS ENV:whdloadargs
  whdload "AotGSAFP27b6.Slave" $whdloadargs
ELSE
  whdload "AotGSAFP27b6.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
