; Clear screen
echo "*ec" NOLINE

fsearch "$ags2dir" PAT #?.ru#? ALL >T:_ags2runfiles1
sed "s/^\(.\)/execute S:AGS2RunUpdate *"\1/" "T:_ags2runfiles1" >"T:_ags2runfiles2"
sed "s/\(.\)$/\1*" *"EXIST*"/" "T:_ags2runfiles2" >"T:_ags2runfiles3"
echo "Updating AGS2 menu '$ags2dir'"
echo "to only show installed entries..."
echo "(this can take several minutes)"
execute "T:_ags2runfiles3"
echo "Done"
echo ""
delete T:_ags2runfiles#? >NIL:
