; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Games:B/BargonAttackFr/BargonAttackFr.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "B" "Bargon Attack FR"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:B/BargonAttackFr/"
IF EXISTS ENV:whdloadargs
  whdload "BargonAttackFr.Slave" $whdloadargs
ELSE
  whdload "BargonAttackFr.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
