; Favourites Mode
IF EXISTS ENV:favouritesmode
	execute S:Favourites "ags2" "0" "688 Attack Sub"
	IF $favouritesmode EQ "add"
		SKIP end
	ENDIF
	IF $favouritesmode EQ "remove"
		SKIP end
	ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Games:0-9/688AttackSub/"
IF EXISTS ENV:whdloadargs
	whdload "688AttackSub.slave" $whdloadargs
ELSE
	whdload "688AttackSub.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end

