; AGS2 run script
; ---------------
;RunFile=A-Games:T/TestDrive2&DataDisks/TestDrive2&DataDisks.slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "T" "Test Drive II The Duel Dat"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Games:T/TestDrive2&DataDisks/"
IF EXISTS ENV:whdloadargs
  whdload "TestDrive2&DataDisks.slave" $whdloadargs
ELSE
  whdload "TestDrive2&DataDisks.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
